main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name="main"),
    path('menu/', views.menu_all_categories, name="menu_all_categories"),
    path('menu/<int:category_id>', views.menu_category_dishes, name="menu_category_dishes"),
    path('cart/', views.show_cart, name="show_cart"),
    path('cart/add/', views.add_to_cart, name="add_to_cart"),
    path('cart/change/', views.change_cart_item, name="change_cart_item"),
    path('cart/delete/', views.delete_cart_item, name="delete_cart_item"),
    path('order/', views.fill_order, name="fill_order"),
    path('delivery/', views.show_delivery, name="show_delivery")
]

uris_diner/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),
    path('backoffice/', include('backoffice.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User

def category_image_path(instance, filename):
    return f'categories/{instance.name}.{filename.split(".")[-1]}'

class Category(models.Model):
    name = models.CharField(max_length=20, blank=False, unique=True)
    is_deleted = models.BooleanField(default=False)
    image_Url = models.URLField(null=True, blank=True)
    image_file = models.ImageField(upload_to=category_image_path, null=True, blank=True)
    position = models.IntegerField(blank=False, default=0)

    def __str__(self):
        return self.name

def dish_image_path(instance, filename):
    return f'dishes/{instance.category.name}/{instance.name}.{filename.split(".")[-1]}'

class Dish(models.Model):
    name = models.CharField(max_length=50, blank=False)
    price = models.DecimalField(max_digits=5, decimal_places=2, blank=False)
    description = models.CharField(max_length=300, blank=False)
    is_gluten_free = models.BooleanField(default=False)
    is_vegeterian = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, limit_choices_to={'is_deleted':False})
    is_deleted = models.BooleanField(default=False)
    image_Url = models.URLField(null=True, blank=True)
    image_file = models.ImageField(upload_to=dish_image_path, null=True, blank=True)

    def __str__(self):
        return self.name

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)

    def __str__(self):
        return f"{self.id}_{self.user.username}"
    
    @property
    def total_to_pay(self):
        total = sum(item.item_total for item in self.item_set.all())
        return total

class Item(models.Model):
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, blank=False)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, blank=False)
    amount = models.IntegerField(blank=False, default=1)

    def __str__(self):
        return f"{self.cart} {self.dish.name}({self.amount})"
    
    @property
    def item_total(self):
        total = self.amount * self.dish.price
        return total

class Delivery(models.Model):
    is_delivered = models.BooleanField(default=False)
    address = models.CharField(max_length=200, blank=False)
    comment = models.CharField(max_length=500, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    order = models.OneToOneField(Cart, primary_key=True, on_delete=models.CASCADE)

templates/forms/CategoryForm.html
<div class="row">
  <div class="col s12 m6 l4">
    <div class="input-field">
      {{form.name.label_tag}}{{form.name}}
      {% for error in form.name.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

{% if form.instance.id != None %}
<div class="row">
  <div class="col s12">
    <div>
      <h6>Dishes in this category:</h6>
      <ol>
        {% for dish in form.instance.dish_set.all %}
        {% if dish.is_deleted == False %}
        <li><a href="{% url 'edit_dish' id=dish.id %}">{{dish.name}}</a></li>
        {% endif %}
        {% endfor %}
      </ol>
    </div>
  </div>
</div>
{% endif %}

<div class="row">
  <div class="col s12">
    {% if form.instance.id != None %}
    <div class="section">
      <p>Current image:</p>
    </div>
    <div>
      {% if form.instance.image_file %}
      <div>
        <img class="category-img" src="{{form.instance.image_file.url}}" alt="">
      </div>
      Uploaded file: {{form.instance.image_file.name}}
      {% else %}
      <div>
        <img class="category-img" src="{{form.instance.image_Url}}" alt="">
      </div>
      <p style="overflow-wrap: break-word">
        Image URL: {{form.instance.image_Url}}
      </p>
      {% endif %}
    </div>
    {% endif %}
    <div class="file-field input-field">
      <div class="btn"><span>{{form.image_file.label}}</span></div>
      {{form.image_file}}
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
    {% for error in form.image_file.errors %}
    <div class="red-text">{{error}}</div>
    {% endfor %}
  </div>
</div>

<div>
  Or
</div>

<div class="row">
  <div class="col s12">
    <div class="input-field tooltipped" data-position="bottom"
      data-tooltip="{{form.image_Url.help_text}}">
      {{form.image_Url.label_tag}} {{form.image_Url}}
      {% for error in form.image_Url.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

{% if form.non_field_errors %}
<div class="red-text row">
  <div class="col">
    {% for error in form.non_field_errors %}
    <div>{{error}}</div>
    {% endfor %}
  </div>
</div>
{% endif %}

templates/forms/ChangeInfoForm.html
<div class="row">
  <div class="col s12 m6">
    <div class="input-field">
      {{form.first_name.label_tag}} {{form.first_name}}
      {% for error in form.first_name.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
  <div class="col s12 m6">
    <div class="input-field">
      {{form.last_name.label_tag}} {{form.last_name}}
      {% for error in form.last_name.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="input-field">
      {{form.email.label_tag}} {{form.email}}
      {% for error in form.email.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

{% if form.non_field_errors %}
<div class="red-text row">
  <div class="col">
    {% for error in form.non_field_errors %}
    <div>{{error}}</div>
    {% endfor %}
  </div>
</div>
{% endif %}

templates/forms/CustomAuthenticationForm.html
<div class="row">
  <div class="col s12">
    <div class="input-field">
      {{form.username.label_tag}} {{form.username}}
      {% for error in form.username.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="input-field">
      {{form.password.label_tag}} {{form.password}}
      {% for error in form.password.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

{% if form.non_field_errors %}
<div class="red-text row">
  <div class="col">
    {% for error in form.non_field_errors %}
    <div>{{error}}</div>
    {% endfor %}
  </div>
</div>
{% endif %}

templates/forms/CustomPasswordChangeForm.html
<div class="row">
  <div class="col s12">
    <div class="input-field">
      {{form.old_password.label_tag}} {{form.old_password}}
      {% for error in form.old_password.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 l6">
    <div class="input-field tooltipped" data-position="bottom"
      data-tooltip="{{form.new_password1.help_text}}">
      {{form.new_password1.label_tag}} {{form.new_password1}}
      {% for error in form.new_password1.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
  <div class="col s12 l6">
    <div class="input-field">
      {{form.new_password2.label_tag}} {{form.new_password2}}
      {% for error in form.new_password2.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

{% if form.non_field_errors %}
<div class="red-text row">
  <div class="col">
    {% for error in form.non_field_errors %}
    <div>{{error}}</div>
    {% endfor %}
  </div>
</div>
{% endif %}

templates/forms/CustomUserCreationForm.html
<div class="row">
  <div class="col s12 m6">
    <div class="input-field">
      {{form.first_name.label_tag}} {{form.first_name}}
      {% for error in form.first_name.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
  <div class="col s12 m6">
    <div class="input-field">
      {{form.last_name.label_tag}} {{form.last_name}}
      {% for error in form.last_name.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="input-field">
      {{form.email.label_tag}} {{form.email}}
      {% for error in form.email.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="input-field tooltipped" data-position="bottom"
      data-tooltip="{{form.username.help_text}}">
      {{form.username.label_tag}} {{form.username}}
      {% for error in form.username.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 l6">
    <div class="input-field tooltipped" data-position="bottom" id="password1"
      data-tooltip="{{form.password1.help_text}}">
      {{form.password1.label_tag}} {{form.password1}}
      {% for error in form.password1.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
  <div class="col s12 l6">
    <div class="input-field tooltipped" data-position="bottom" id="password2"
      data-tooltip="{{form.password2.help_text}}">
      {{form.password2.label_tag}} {{form.password2}}
      {% for error in form.password2.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

{% if form.non_field_errors %}
<div class="red-text row">
  <div class="col">
    {% for error in form.non_field_errors %}
    <div>{{error}}</div>
    {% endfor %}
  </div>
</div>
{% endif %}

<script>
  let isMobile = window.matchMedia("(max-width: 600px)").matches
  let password1 = document.getElementById("password1");
  let password2 = document.getElementById("password2");
  if (isMobile) {
    password1.dataset.position = "top";
    password2.dataset.position = "top";
  }
</script>

templates/forms/DishForm.html
<div class="row">
  <div class="col s12 m6">
    <div class="input-field">
      {{form.name.label_tag}} {{form.name}}
      {% for error in form.name.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
  <div class="col s4 m2">
    <div class="input-field">
      {{form.price.label_tag}} {{form.price}}
      {% for error in form.price.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
  <div class="col s8 m4">
    <div class="input-field">
      {{form.category}} {{form.category.label_tag}}
      {% for error in form.category.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="input-field">
      {{form.description.label_tag}}{{form.description}}
      {% for error in form.description.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12 m4 xl2">
    <p>
      <label>
        <input type="checkbox" class="filled-in"
          name="{{form.is_vegeterian.name}}"
          {% if form.is_vegeterian.initial == True %} checked="checked"
          {% endif %} />
        <span>{{form.is_vegeterian.label}}</span>
      </label>
    </p>
  </div>
  <div class="col s12 m4">
    <p>
      <label>
        <input type="checkbox" class="filled-in"
          name="{{form.is_gluten_free.name}}"
          {% if form.is_gluten_free.initial == True %} checked="checked"
          {% endif %} />
        <span>{{form.is_gluten_free.label}}</span>
      </label>
    </p>
  </div>
</div>

<div class="row">
  <div class="col s12">
    {% if form.instance.id != None %}
    <div class="section">
      <p>Current image:</p>
    </div>
    <div>
      {% if form.instance.image_file %}
      <div>
        <img class="dish-img big" src="{{form.instance.image_file.url}}" alt="">
      </div>
      Uploaded file: {{form.instance.image_file.name}}
      {% else %}
      <div>
        <img class="dish-img big" src="{{form.instance.image_Url}}" alt="">
      </div>
      <p style="overflow-wrap: break-word">
        Image URL: {{form.instance.image_Url}}
      </p>
      {% endif %}
    </div>
    {% endif %}
    <div class="file-field input-field">
      <div class="btn"><span>{{form.image_file.label}}</span></div>
      {{form.image_file}}
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
    {% for error in form.image_file.errors %}
    <div class="red-text">{{error}}</div>
    {% endfor %}
  </div>
</div>

<div>
  Or
</div>

<div class="row">
  <div class="col s12">
    <div class="input-field tooltipped" data-position="bottom"
      data-tooltip="{{form.image_Url.help_text}}">
      {{form.image_Url.label_tag}} {{form.image_Url}}
      {% for error in form.image_Url.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

{% if form.non_field_errors %}
<div class="red-text row">
  <div class="col">
    {% for error in form.non_field_errors %}
    <div>{{error}}</div>
    {% endfor %}
  </div>
</div>
{% endif %}

templates/forms/OrderForm.html
<div class="row">
  <div class="col s12">
    <div class="input-field">
      {{form.address.label_tag}} {{form.address}}
      {% for error in form.address.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="row">
  <div class="col s12">
    <div class="input-field">
      {{form.comment.label_tag}} {{form.comment}}
      {% for error in form.comment.errors %}
      <div class="red-text">{{error}}</div>
      {% endfor %}
    </div>
  </div>
</div>

{% if form.non_field_errors %}
<div class="red-text row">
  <div class="col">
    {% for error in form.non_field_errors %}
    <div>{{error}}</div>
    {% endfor %}
  </div>
</div>
{% endif %}